server:
  port: 8888
  servlet:
    context-path: "/dynamic-tp"

spring:
  application:
    name: dynamic-tp-apollo-demo
  profiles:
    active: dev


logging:
  level:
    #root: DEBUG
    com.alibaba.nacos.client.config.impl: WARN

apollo:
  bootstrap:
    enabled: true
    namespaces: dynamic-tp-apollo-demo-dtp.yml
  meta: http://localhost:8080
  config-service: http://localhost:8080
app:
  id: dynamic-tp-apollo-demo